development:
  adapter: mysql2
  encoding: utf8
  database: english_drill_react_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: english_drill_react_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: english_drill_react_production
  pool: 5
  username: root
  password:
